### PR TITLE
Issues/67 jquery check

### LINKED ISSUE #67: Incorrect check for jquery, and no mention of jquery dependency in the doc
Correct me I'm off track here, but it seems that this uses JQuery for animations, however I see no reference made to JQuery in the readme.
There's also a check:
`if (animate && $) {`
https://github.com/aullman/opentok-layout-js/blob/master/src/layout.js#L65
but if $ is not defined this throws:
`ReferenceError: $ is not defined`

### PR DESCRIPTION
**Pull request by maikthomas**
Fixes #67

### CODE REVIEW

File: opentok-layout.js.map [hunk 1]
```diff
@@ -1 +0,0 @@
...t - offsetTop, offsetLeft, offsetTop,\n        opts.fixedRatio, opts.minRatio, opts.maxRatio, opts.animate);\n    }\n  };\n\n  var initLayoutContainer = function(container, opts) {\n    opts = defaults(opts || {}, {\n      maxRatio: 3 / 2,\n      minRatio: 9 / 16,\n      fixedRatio: false,\n      animate: false,\n      bigClass: 'OT_big',\n      bigPercentage: 0.8,\n      bigFixedRatio: false,\n      bigMaxRatio: 3 / 2,\n      bigMinRatio: 9 / 16,\n      bigFirst: true\n    });\n    container = typeof(container) === 'string' ? document.querySelector(container) : container;\n\n    if (document.readyState === 'complete') {\n      layout(container, opts);\n    } else {\n      window.addEventListener('load', function() {\n        layout(container, opts);\n      });\n    }\n\n    return {\n      layout: layout.bind(null, container, opts)\n    };\n  };\n\n  if (typeof module === 'undefined' || typeof module.exports === 'undefined') {\n    window.initLayoutContainer = initLayoutContainer;\n  } else {\n    module.exports.initLayoutContainer = initLayoutContainer;\n  }\n\n})((typeof window !== 'undefined' && window.hasOwnProperty('jQuery')) ? window.jQuery : undefined);\n"],"sourceRoot":""}
```
Comment (maikthomas) [inline opentok-layout.js.map:1]: I deleted this file and it was not regenerated in the build... where did it come from originally? 
Is a map needed for the non-minimized file? 🤔

Comment (aullman) [reply opentok-layout.js.map:1]: Ha, no good point I don't think it's needed and you're right webpack doesn't generate one. My only guess is that I messed up and accidentally generated a map with the wrong file name and committed that file.
